### ISSUE TITLE
re-launching tasks after restart fails with "Task has duplicate ID"

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#158] opened 2017-07-04 04:02 UTC
Using the Retz client I have started a job and submitted it to Retz:

```
./bin/retz-client -C retz.properties run -A your-test-app -cmd "sleep 50"
```

After the job was started on Mesos I killed the Retz server, which does not kill the running task automatically. When restarting Retz, it tries to start the job again:

```
2017-07-04 12:52:31.319 INFO  [main] io.github.retz.scheduler.Launcher - 1 jobs found in DB 'STARTING' or 'STARTED' state. Requeuing...
2017-07-04 12:52:31.385 WARN  [main] io.github.retz.scheduler.Launcher - Unknown job!
  (repeated many times)
2017-07-04 12:52:31.411 WARN  [main] io.github.retz.scheduler.Launcher - Unknown job!
2017-07-04 12:52:31.473 INFO  [main] io.github.retz.scheduler.Launcher - 1 jobs rescheduled, 0 jobs didn't need change.
2017-07-04 12:52:31.477 INFO  [main] i.g.retz.scheduler.RetzScheduler - Server name in HTTP(S) header: retz-server-0.2.8-SNAPSHOT (0.0.31-233-g08bbe93)
  (...)
2017-07-04 12:52:31.969 INFO  [Thread-3] org.eclipse.jetty.server.Server - Started @2179ms
2017-07-04 12:52:32.047 INFO  [pool-3-thread-1] io.github.retz.db.Database - TaskId of id=1603: retz-your-test-app-id-1603 / retz-your-test-app-id-1603
2017-07-04 12:52:32.059 INFO  [pool-3-thread-1] io.github.retz.db.Database - Job (id=1603) status updated to STARTING
2017-07-04 12:52:32.072 INFO  [Thread-15] i.g.retz.scheduler.RetzScheduler - Status update of task retz-your-test-app-id-1603: TASK_ERROR / Task has duplicate ID: retz-your-test-app-id-1603 (REASON_TASK_INVALID)
2017-07-04 12:52:32.131 INFO  [pool-3-thread-1] io.github.retz.db.Database - Job (id=1603) status updated to KILLED
2017-07-04 12:52:32.132 INFO  [pool-3-thread-1] io.github.retz.scheduler.JobQueue - Job id=1603 has failed: Task has duplicate ID: retz-your-test-app-id-1603
```

It seems as if the reason is that Retz is requeuing jobs that *are already* "`STARTING` or `STARTED`". Is there any particular reasoning behind that?

**Comment by kuenishi** [comment] 2017-07-25 06:45
My design (apparently the software doesn't work as intended) is:

1. Retz restarts and connects to Mesos master with *same* framework id
2. Retz scans all running or pre-running tasks on Mesos via operator API
3. Retz scans all running or pre-running jobs in its database
4. Retz compares two lists and updates all job informations in database,
      * rollbacks a job state to `QUEUED` if there's no corresponding task in Mesos
      * updates a job state to `FINISHED` or `KILLED` if corresponding task in Mesos is finished / killed /failed, and
      * resolves any other inconsistent job states to update its database, considering Mesos master failure or network separation between Retz and Mesos.
 
But I should simplify all those complex logic to just using reconcile functionality of driver API and `statusUpdate` scheduler API.

**Comment by kuenishi** [comment] 2017-07-25 06:48
Also, do you know what happened to Retz after running task `id=1603` has finished? Can you give the result of `retz-client get-job --id 1603` after 50 seconds has passed?

**Comment by tgpfeiffer** [comment] 2017-09-12 08:44
Release 0.4.0 has fixed the problem, thank you very much! When I restart Retz, I see

> 2017-09-12 17:31:32.369 INFO  [pool-3-thread-1] io.github.retz.db.Database - Job (id=2929) status updated to STARTED

in the logs and the job continues running. :+1:

However, it seems as if the timestamp of the job start is also updated at that point in time, which does not represent the real start date any more. (I have run a command `sleep 200`, but judging from the start and end timestamps stored in the database it has run only 56 seconds and started at the time when the Retz server was started.) Maybe it is possible to check (in that particular situation) whether a start timestamp already exists and only update it if not?

**Comment by kuenishi** [comment] 2017-09-20 07:45
I think I have fixed @tgpfeiffer 's concern at https://github.com/retz/retz/commit/619b27d5423f6dfa83a40d728aef27b3b93a7eaa thus closing this issue. Feel free to open a new one if it's still an issue.

**Closed as completed by kuenishi** 2017-09-20 07:45 UTC
Labels: bug
