### ISSUE TITLE
HTTP 500 when running list-files on a symlinked directory

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#101] opened 2016-12-09 01:05 UTC
I have a symlink in my sandbox that points to an outside directory, but when I run `list-files` with that symlink as a `--path`, then the server returns a HTTP 500 status code. While the underlying reason maybe comes from Mesos (cf. https://issues.apache.org/jira/browse/MESOS-4217), I guess 500 is not the best response code for that.

**Comment by kuenishi** [comment] 2016-12-14 04:37
I couldn't reproduce this in both current master HEAD 753ab4868fda527269f5a and 0.1.1, on Mesos 1.1.0 . In MESOS-4217 some people says it's no more reproducible (and somehow fixed..).  If it's still reproducible for you, could you elaborate more information on your enviornment such as versions, and how to reproduce?

**Comment by tgpfeiffer** [comment] 2016-12-14 12:35
Did you try it with a symlink *inside* or *outside* your sandbox? Do you see the contents of the symlinked directory? In the issue the developers said that sandbox-internal links work fine, sandbox-external links are not supposed to work for security reasons. I guess I can accept the latter, but still 500 shouldn't happen.

**Comment by kuenishi** [comment] 2016-12-15 01:04
Ah, I that makes sense and I reproduced. Yes, 500 should not happen (actually Mesos returns 400 and it is unintentionally translated).

**Comment by kuenishi** [comment] 2016-12-15 07:11
https://github.com/retz/retz/commit/e334defb2abd0def1641963a2c8a183d01dbe392 should be the fix for this. Will be included in 0.1.3 or later.

**Comment by kuenishi** [comment] 2017-07-12 09:49
0.1.3 was released. Feel free to reopen if any further issues related to this.

**Closed as completed by kuenishi** 2017-07-12 09:49 UTC
Labels: bug
